hmpps.sqs:
  provider: localstack
  queues:
    whereabouts:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: prisonerevents
      subscribeFilter: >-
        {"eventType": ["DATA_COMPLIANCE_DELETE-OFFENDER"]}
  topics:
    prisonerevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}