hmpps.sqs:
  provider: localstack
  queues:
    whereabouts:
      queueName: whereabouts_api_queue
      dlqName: whereabouts_api_dlq
    domainevent:
      queueName: domainevent_api_queue
      dlqName: domainevent_api_dlq
