hmpps.sqs:
  provider: localstack
  queues:
    whereabouts:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: prisonerevents
      subscribeFilter: >-
        {"eventType": [
          "DATA_COMPLIANCE_DELETE-OFFENDER",
          "APPOINTMENT_CHANGED"
        ]}
    domainevent:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: domainevents
      subscribeFilter: >-
        {"eventType": [
          "prison-offender-events.prisoner.released"
        ]}
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    prisonerevents:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}