---
# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: whereabouts-api

ingress:
  # live-1 is blue, live is green
  contextColour: green

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 512Mi