# Values here are the same across all environments
generic-service:

  replicaCount: 4

  serviceAccountName: whereabouts-api
  productId: DPS024

  image:
    repository: quay.io/hmpps/whereabouts-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local
    tlsSecretName: whereabouts-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 512Mi

  env:
    JAVA_OPTS: "-Xmx512m"
    SPRING_PROFILES_ACTIVE: "postgres,logstash"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_SQS_USE_WEB_TOKEN: "true"

  namespace_secrets:
    whereabouts-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "OAUTH_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "OAUTH_CLIENT_SECRET"
      NOTIFY_API_KEY: "NOTIFY_API_KEY"
    feature-toggles:
      FEATURE_LISTEN_FOR_COURT_EVENTS: "FEATURE_LISTEN_FOR_COURT_EVENTS"
      FEATURE_EVENT_WHEREABOUTS_API_VIDEOLINK_MIGRATE: "FEATURE_SEND_VIDEO_BOOKING_MIGRATE_EVENTS"
    dps-rds-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    whereabouts-api-sqs-instance-output:
      HMPPS_SQS_QUEUES_WHEREABOUTS_QUEUE_NAME: "sqs_wb_name"
    whereabouts-api-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_WHEREABOUTS_DLQ_NAME: "sqs_wb_name"
    whereabouts-api-domain-events-sqs-instance-output:
      HMPPS_SQS_QUEUES_DOMAINEVENT_QUEUE_NAME: "sqs_name"
    whereabouts-api-domain-events-sqs-dl-instance-output:
      HMPPS_SQS_QUEUES_DOMAINEVENT_DLQ_NAME: "sqs_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: whereabouts-api
