---
# Values here are the same across all environments

generic-prometheus-alerts:
  targetApplication: whereabouts-api

ingress:
  # live-1 is blue, live is green
  contextColour: green
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "0"
    nginx.ingress.kubernetes.io/custom-http-errors: "418"

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 512Mi