# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generic-service:
  replicaCount: 2

  ingress:
    host: whereabouts-api-preprod.service.justice.gov.uk

  env:
    ELITE2API_ENDPOINT_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    OAUTH_ENDPOINT_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    CASENOTES_ENDPOINT_URL: "https://preprod.offender-case-notes.service.justice.gov.uk"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    NOTIFY_ENABLED: false
    PRISONREGISTER_ENDPOINT_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    LOCATIONAPI_ENDPOINT_URL: "https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk"
    WHEREABOUTS_DISABLED: RSI,WDI,LPI,FMI,IWI,WMI,GTI,FKI,LTI,BCI,FNI,MTI,LEI

  namespace_secrets:
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_DOMAINEVENTS_ARN: "topic_arn"
