generic-service:
  replicaCount: 2

  ingress:
    host: whereabouts-api-dev.service.justice.gov.uk

  env:
    ELITE2API_ENDPOINT_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    CASENOTES_ENDPOINT_URL: "https://dev.offender-case-notes.service.justice.gov.uk"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    WHEREABOUTS_DISABLED: RSI,WDI,LPI,FMI,IWI,WMI,GTI,FKI,LTI,BCI,FNI,MTI,LEI,FSI,DMI,HII,WII,RCI,RNI,MDI,LFI,LHI,EYI,PDI,SLI,SNI,BXI,NMI,PVI

  allowlist:
    groups:
      - internal
