generic-service:
  replicaCount: 2

  ingress:
    host: whereabouts-api-dev.service.justice.gov.uk

  env:
    ELITE2API_ENDPOINT_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    OAUTH_ENDPOINT_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    CASENOTES_ENDPOINT_URL: "https://dev.offender-case-notes.service.justice.gov.uk"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json"
    NOTIFY_ENABLED: true
    PRISONREGISTER_ENDPOINT_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    FEATURE_BVLS_ENABLED: "false"

  allowlist:
    groups:
      - internal
