DROP TABLE IF EXISTS ATTENDANCE_CHANGES;

CREATE TABLE ATTENDANCE_CHANGES
(
    ID SERIAL PRIMARY KEY,
    ATTENDANCE_ID BIGINT REFERENCES OFFENDER_ATTENDANCE (ID),
    CHANGED_FROM VARCHAR(30) NOT NULL,
    CHANGED_TO VARCHAR(30) NOT NULL,
    CREATE_DATETIME TIMESTAMP NOT NULL,
    CREATE_USER_ID VARCHAR(32),
    MODIFY_DATETIME TIMESTAMP,
    MODIFY_USER_ID VARCHAR(32)
);

COMMENT ON TABLE ATTENDANCE_CHANGES IS 'Records all changes made to an attendance at an event for an offender';

CREATE INDEX ATTENDANCE_CHANGES_BY_ID_IDX ON ATTENDANCE_CHANGES (ID);
CREATE INDEX ATTENDANCE_CHANGES_BY_ID_CHANGED_TO_CHANGED_FROM_IDX ON ATTENDANCE_CHANGES (ID, CHANGED_TO, CHANGED_FROM);
CREATE INDEX ATTENDANCE_CHANGES_BY_CHANGED_TO_CHANGED_FROM_IDX ON ATTENDANCE_CHANGES (CHANGED_TO, CHANGED_FROM);
