DROP TABLE IF EXISTS MAIN_RECURRING_APPOINTMENT;

CREATE TABLE MAIN_RECURRING_APPOINTMENT
(
    ID            SERIAL PRIMARY KEY,
    REPEAT_PERIOD VARCHAR(20),
    COUNT         INT
);

COMMENT ON TABLE MAIN_RECURRING_APPOINTMENT IS 'Records the main recurring appointments made through dps';

CREATE INDEX MAIN_RECURRING_APPOINTMENT_BY_ID_IDX ON MAIN_RECURRING_APPOINTMENT (ID);

