DROP TABLE IF EXISTS RECURRING_APPOINTMENT;

CREATE TABLE RECURRING_APPOINTMENT
(
    ID                            SERIAL PRIMARY KEY,
    MAIN_RECURRING_APPOINTMENT_ID BIGINT REFERENCES MAIN_RECURRING_APPOINTMENT (ID)
);

COMMENT ON TABLE RECURRING_APPOINTMENT IS 'Record individual appointment that was created as part of a recurring appointment';

CREATE INDEX RECURRING_APPOINTMENT_BY_BOOKING_ID_IDX ON RECURRING_APPOINTMENT (MAIN_RECURRING_APPOINTMENT_ID);

