DROP INDEX MAIN_RECURRING_APPOINTMENT_BY_ID_IDX;
DROP INDEX RECURRING_APPOINTMENT_BY_MAIN_RECURRING_APPOINTMENT_ID_IDX;

ALTER TABLE RECURRING_APPOINTMENT
    RENAME TO APPOINTMENT;

ALTER TABLE MAIN_RECURRING_APPOINTMENT
    RENAME TO RECURRING_APPOINTMENT;

ALTER TABLE APPOINTMENT
    RENAME COLUMN MAIN_RECURRING_APPOINTMENT_ID TO RECURRING_APPOINTMENT_ID;

CREATE INDEX RECURRING_APPOINTMENT_BY_ID_IDX ON RECURRING_APPOINTMENT (ID);

CREATE INDEX APPOINTMENT_BY_RECURRING_APPOINTMENT_ID_IDX ON APPOINTMENT (RECURRING_APPOINTMENT_ID);