DELETE FROM ABSENT_REASONS;

INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE, PAID_REASON) VALUES (1, 'Acceptable absence', 'ACCAB', true);
INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE, PAID_REASON) VALUES (2, 'Not required', 'NREQ', true);


INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE) VALUES (3, 'Session Cancelled', 'CANC');
INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE) VALUES (4, 'Rest in cell', 'REST');
INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE) VALUES (5, 'Sick', 'REST');
INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE) VALUES (6, 'Rest Day', 'REST');
INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE) VALUES (7, 'Unacceptable absence', 'UNACAB');
INSERT INTO ABSENT_REASONS (ID,REASON, PNOMIS_CODE) VALUES (8, 'Refused', 'UNACAB');




