insert into enabled_court (id, name) values
(   'BRNSMC', 'Barnsley Magistrates'),
(   'BDLNMC', 'Bedlington Magistrates'),
(   'BEVRMC', 'Beverley Magistrates'),
(   'BRADCT', 'Bradford County'),
(   'BRADCC', 'Bradford Crown'),
(   'BRADMC', 'Bradford Magistrates'),
(   'CARLCT', 'Carlisle County'),
(   'CARLCC', 'Carlisle Crown'),
(   'CARLMC', 'Carlisle Magistrates'),
(   'DONCCT', 'Doncaster County'),
(   'DONCCC', 'Doncaster Crown'),
(   'DONCMC', 'Doncaster Magistrates'),
(   'DURHCT', 'Durham County'),
(   'DURHCC', 'Durham Crown'),
(   'GTSHMC', 'Gateshead Magistrates'),
(   'GRIMCT', 'Grimsby County'),
(   'GRIMCC', 'Grimsby Crown'),
(   'GRIMMC', 'Grimsby Magistrates'),
(   'HRRGMC', 'Harrogate Magistrates'),
(   'KNGHCT', 'Hull County'),
(   'KINGCC', 'Hull Crown'),
(   'KNGHMC', 'Hull Magistrates'),
(   'HUDRMC', 'Kirklees Magistrates'),
(   'LEEDCC', 'Leeds County'),
(   'LEEDCT', 'Leeds Crown'),
(   'LEEDMC', 'Leeds Magistrates'),
(   'NWCSCT', 'Newcastle-Upon-Tyne County'),
(   'NWCSCC', 'Newcastle-Upon-Tyne Crown'),
(   'NWCSMC', 'Newcastle-Upon-Tyne Magistrates'),
(   'NWAYMC', 'Newton Aycliffe Magistrates'),
(   'NRTSMC', 'North Tyneside Magistrates'),
(   'PTRLMC', 'Peterlee Magistrates'),
(   'SCBNMC', 'Scarborough Magistrates'),
(   'SHEFCT', 'Sheffield County'),
(   'SHEFCC', 'Sheffield Crown'),
(   'SHEFMC', 'Sheffield Magistrates'),
(   'STHMMC', 'South Tyneside Magistrates'),
(   'SUNDMC', 'Sunderland Magistrates'),
(   'TEESCT', 'Teesside County'),
(   'MDDLMC', 'Teesside Magistrates'),
(   'TEESCC', 'Teesside Crown'),
(   'WORNMC', 'Workington Magistrates'),
(   'YORKCT', 'York County'),
(   'YORKCC', 'York Crown'),
(   'YORKMC', 'York Magistrates');
