ALTER TABLE OFFENDER_ATTENDANCE
    ALTER COLUMN ABSENT_REASON TYPE VARCHAR(40);

UPDATE OFFENDER_ATTENDANCE
SET ABSENT_REASON = 'UnacceptableAbsenceIncentiveLevelWarning'
WHERE ABSENT_REASON = 'UnacceptableAbsence';
