ALTER TABLE ATTENDANCE_CHANGES
    ALTER COLUMN CHANGED_FROM TYPE VARCHAR(40);

ALTER TABLE ATTENDANCE_CHANGES
    ALTER COLUMN CHANGED_TO TYPE VARCHAR(40);

UPDATE ATTENDANCE_CHANGES
SET CHANGED_FROM = 'UnacceptableAbsenceIncentiveLevelWarning'
WHERE CHANGED_FROM = 'UnacceptableAbsence';

UPDATE ATTENDANCE_CHANGES
SET CHANGED_TO = 'UnacceptableAbsenceIncentiveLevelWarning'
WHERE CHANGED_TO = 'UnacceptableAbsence';
