ALTER TABLE  OFFENDER_ATTENDANCE
ADD COLUMN CREATE_DATETIME  TIMESTAMP NOT NULL;

ALTER TABLE  OFFENDER_ATTENDANCE
ADD COLUMN CREATE_USER_ID  VARCHAR( 32)    NOT NULL;

ALTER TABLE  OFFENDER_ATTENDANCE
ADD COLUMN MODIFY_DATETIME TIMESTAMP;

ALTER TABLE  OFFENDER_ATTENDANCE
ADD COLUMN MODIFY_USER_ID VARCHAR( 32);

ALTER TABLE OFFENDER_ATTENDANCE
ADD COLUMN CASE_NOTE_ID BIGINT;
