insert into enabled_court (id, name) values
('CRT027','Barkingside Magistrates'),
('BRNTCT','Barnet Civil and Family Court'),
('BSLDCT', 'Basildon County'),
('BSLDCC', 'Basildon Crown'),
('BSLDMC', 'Basildon Magistrates'),
('BEXLMC', 'Bexley Magistrates'),
('BRTFCT', 'Brentford Civil and Family Court'),
('BRGHCT', 'Brighton County'),
('BRGEMC', 'Brighton Magistrates'),
('CNTRCC', 'Central Criminal Court'),
('CHLMCC', 'Chelmsford Crown'),
('CHLMMC', 'Chelmsford Magistrates'),
('CLRKCT', 'Clerkenwell and Shoreditch County'),
('COLTMC', 'Colchester Magistrates'),
('CRAWMC', 'Crawley Magistrates'),
('DRTFCT', 'Dartford County Court and Family Court'),
('EALNMC', 'Ealing Magistrates'),
('HRRWCC', 'Harrow Crown'),
('HSTNCT', 'Hastings County'),
('HSTNMC', 'Hastings Magistrates'),
('HATFMC', 'Hatfield Magistrates'),
('HNDNMC', 'Hendon Magistrates'),
('HERTCT', 'Hertford County and Family Court'),
('HWYCCT', 'High Wycombe County Court'),
('HGHBMC', 'Highbury Corner Magistrates'),
('HRSHCT', 'Horsham County'),
('HRSHMC', 'Horsham Magistrates'),
('LEWSCT', 'Lewes Crown'),
('LUTNMC', 'Luton and South Bedfordshire Magistrates'),
('LUTNCC', 'Luton Crown'),
('MLTKCT', 'Milton Keynes County Court and Family Court'),
('OXFDCT', 'Oxford County'),
('PBORCT', 'Peterborough County'),
('READCT', 'Reading County Court and Family Court'),
('RMFRCT', 'Romford County'),
('RMFRMC', 'Romford Magistrates'),
('SLOUCT', 'Slough County Court and Family Court'),
('STHSCC', 'Southend Crown'),
('STHSMC', 'Southend Magistrates'),
('STALCC', 'St Albans Crown'),
('STALMC', 'St Albans Magistrates'),
('STEVMC', 'Stevenage Magistrates'),
('STRAMC', 'Stratford Magistrates'),
('THANCT', 'Thanet County Court and Family Court'),
('UXBRMC', 'Uxbridge Magistrates'),
('WATFCT', 'Watford County and Family Court'),
('CRT026', 'Willesden Magistrates'),
('WORTCT', 'Worthing County'),
('WORTMC', 'Worthing Magistrates'),
('BRIGFC', 'Brighton Family'),
('BROCFC', 'Bromley Civil and Family'),
('CENTFC', 'Central Family Court'),
('CHELJC', 'Chelmsford Justice Centre'),
('CRDCFC', 'Croydon Civil and Family'),
('ELONFC', 'East London Family Court'),
('ELTARB', 'East London Tribunals - Asylum Support'),
('EDMTFC', 'Edmonton Civil and Family'),
('GUCTFC', 'Guildford County Court and Family Court'),
('HASTFC', 'Hastings Family'),
('HORSFC', 'Horsham Family'),
('IACHRM', 'IAC Harmondsworth'),
('KNGTCT', 'Kingston upon Thames County Court'),
('LTONJC', 'Luton Justice Centre'),
('RCJCNM', 'RCJ - Chancery Masters'),
('RCJLCT', 'RCJ - County Court at Central London'),
('RCJCAC', 'RCJ - Court of Appeal Civil'),
('RCJCCC', 'RCJ – Court of Appeal Criminal'),
('RCJHAC', 'RCJ - High Court Administrative Court'),
('RCJHFC', 'RCJ - High Court Family Division'),
('RCJKBJ', 'RCJ - High Court Kings Bench (Judges)'),
('RCJKBM', 'RCJ - High Court Kings Bench (Masters)'),
('RCJIAC', 'RCJ - Insolvency and Companies'),
('RCJMAC', 'RCJ - Mayors and City'),
('SSSCST', 'Sutton Social Security and Child Support Tribunal'),
('UTIACH', 'UTIAC Field House'),
('UXCAFC', 'Uxbridge Civil and Family Court'),
('WNDCFC', 'Wandsworth Civil and Family'),
('WLONFC', 'West London Family Court'),
('WDECFC', 'Willesden Civil and Family'),
('WORGFC', 'Worthing Family');
