insert into enabled_court (id, name) values
('CRT027','Barkingside Magistrates'),
('BRNTCT','Barnet Civil and Family Court'),
('BSLDCT', 'Basildon County'),
('BSLDCC', 'Basildon Crown'),
('BSLDMC', 'Basildon Magistrates'),
('BEXLMC', 'Bexley Magistrates'),
('BRTFCT', 'Brentford Civil and Family Court'),
('BRGHCT', 'Brighton County'),
('BRGEMC', 'Brighton Magistrates'),
('CNTRCC', 'Central Criminal Court'),
('CHLMCC', 'Chelmsford Crown'),
('CHLMMC', 'Chelmsford Magistrates'),
('CLRKCT', 'Clerkenwell and Shoreditch County'),
('COLTMC', 'Colchester Magistrates'),
('CRAWMC', 'Crawley Magistrates'),
('DRTFCT', 'Dartford County Court and Family Court'),
('EALNMC', 'Ealing Magistrates'),
('HRRWCC', 'Harrow Crown'),
('HSTNCT', 'Hastings County'),
('HSTNMC', 'Hastings Magistrates'),
('HATFMC', 'Hatfield Magistrates'),
('HNDNMC', 'Hendon Magistrates'),
('HERTCT', 'Hertford County and Family Court'),
('HWYCCT', 'High Wycombe County Court'),
('HGHBMC', 'Highbury Corner Magistrates'),
('HRSHCT', 'Horsham County'),
('HRSHMC', 'Horsham Magistrates'),
('LEWSCT', 'Lewes Crown'),
('LUTNMC', 'Luton and South Bedfordshire Magistrates'),
('LUTNCC', 'Luton Crown'),
('MLTKCT', 'Milton Keynes County Court and Family Court'),
('OXFDCT', 'Oxford County'),
('PBORCT', 'Peterborough County'),
('READCT', 'Reading County Court and Family Court'),
('RMFRCT', 'Romford County'),
('RMFRMC', 'Romford Magistrates'),
('SLOUCT', 'Slough County Court and Family Court'),
('STHSCC', 'Southend Crown'),
('STHSMC', 'Southend Magistrates'),
('STALCC', 'St Albans Crown'),
('STALMC', 'St Albans Magistrates'),
('STEVMC', 'Stevenage Magistrates'),
('STRAMC', 'Stratford Magistrates'),
('THANCT', 'Thanet County Court and Family Court'),
('UXBRMC', 'Uxbridge Magistrates'),
('WATFCT', 'Watford County and Family Court'),
('CRT026', 'Willesden Magistrates'),
('WORTCT', 'Worthing County'),
('WORTMC', 'Worthing Magistrates');
