insert into enabled_court (id, name) values
('TRURCC', 'Truro Crown'),
('TRURMC', 'Truro Magistrates'),
('CBODMC', 'Bodmin Magistrates'),
('PLYMCC', 'Plymouth Crown'),
('PLYMMC', 'Plymouth Magistrates'),
('NWTAMC', 'Newton Abbot Magistrates'),
('EXETCC', 'Exeter Crown'),
('EXETMC', 'Exeter Magistrates'),
('BNSTMC', 'Barnstaple Magistrates'),
('WEYMMC', 'Weymouth Magistrates'),
('BRNMCC', 'Bournemouth Crown'),
('POOLMC', 'Poole Magistrates'),
('TAUNCC', 'Taunton Crown'),
('TAUNMC', 'Taunton Magistrates'),
('YEOVMC', 'Yeovil Magistrates'),
('BATHMC', 'Bath Magistrates'),
('WSPMMC', 'Weston-Super-Mare Magistrates'),
('BRSTCC', 'Bristol Crown'),
('BRSTMC', 'Bristol Magistrates'),
('SALSCC', 'Salisbury Crown'),
('SALSMC', 'Salisbury Magistrates'),
('SOUTCC', 'Southampton Crown'),
('SOUTMC', 'Southampton Magistrates'),
('WNCHCC', 'Winchester Crown'),
('BSNGMC', 'Basingstoke Magistrates'),
('ALDRMC', 'Aldershot Magistrates'),
('PRTSMC', 'Portsmouth Magistrates'),
('PRTSCC', 'Portsmouth Crown'),
('IOWICC', 'Isle of Wight Crown'),
('IOWIMC', 'Isle of Wight Magistrates'),
('LINCCC', 'Lincoln Crown'),
('LINCMC', 'Lincoln Magistrates'),
('BOSTMC', 'Boston Magistrates'),
('RCULON', 'RCU - London'),
('RCUMID', 'RCU - Midlands'),
('RCUNOR', 'RCU - North'),
('RCUSET', 'RCU - South East'),
('RCUWSW', 'RCU - Wales and South West'),
('PPOCFD', 'PPoC - Field'),
('PPOCCT', 'PPoC - Court Team');
