insert into enabled_court (id, name) values
('CHESCC', 'Chester Crown'),
('CHESMC', 'Chester Magistrates'),
('CREWMC', 'Crewe Magistrates'),
('LPOLCC', 'Liverpool Crown'),
('LPOLMC', 'Liverpool Magistrates'),
('SEFTMC', 'Sefton Magistrates'),
('WRRNMC', 'Warrington Magistrates'),
('WIRLMC', 'Wirral Magistrates'),
('ENFLON', 'ENF - London'),
('REMPSR', 'Probation - Remote PSR Team (PPOC)'),
('CROYCC', 'Probation - CRO - Croydon CC (PPOC)'),
('CROYMC', 'Probation - CRO - Croydon MC (PPOC)'),
('ILONCC', 'Probation - SOU - Inner London CC (PPOC)'),
('SWRKCC', 'Probation - SOU - Southwark CC (PPOC)'),
('KENSCC', 'Probation - KAR - Kingston CC (PPOC)'),
('HFKCW', 'Probation - HFKCW - Westminster MC (PPOC)'),
('WIMBMC', 'Probation - WAN - Wimbledon MC (PPOC)'),
('HARNGY', 'Probation - EAH - Haringey (PPOC)'),
('BARNET', 'Probation - BAR - Barnet (PPOC)'),
('HARROW', 'Probation - HRW - Harrow (PPOC)'),
('WALFOR', 'Probation - RWF - Waltham Forest (PPOC)')
