insert into enabled_court (id, name)
values ('ABERMC', 'Aberystwyth Magistrates'),
       ('CARDCC', 'Cardiff Crown'),
       ('CARDMC', 'Cardiff Magistrates'),
       ('CWMBMC', 'Cwmbran Magistrates'),
       ('HAVEMC', 'Haverfordwest Magistrates'),
       ('HAVECC', 'Haverfordwest Crown'),
       ('LLANMC', 'Llanelli Magistrates'),
       ('MERTCC', 'Merthyr Tydfil Crown'),
       ('MERTMC', 'Merthyr Tydfil Magistrates'),
       ('NEWPCC', 'Newport Crown'),
       ('NEWPMC', 'Newport Magistrates'),
       ('SWANCC', 'Swansea Crown'),
       ('SWANMC', 'Swansea Magistrates'),
       ('ABERCV', 'Aberystwyth Civil'),
       ('ABERFC', 'Aberystwyth Family'),
       ('BLACCV', 'Blackwood Civil'),
       ('BLACFC', 'Blackwood Family'),
       ('CARDCV', 'Cardiff Civil'),
       ('CARDFC', 'Cardiff Family'),
       ('CARMCV', 'Carmarthen Civil'),
       ('CARMFC', 'Carmarthen Family'),
       ('HAVECV', 'Haverfordwest Civil'),
       ('HAVEFC', 'Haverfordwest Family'),
       ('LLANCV', 'Llanelli Civil'),
       ('LLANFC', 'Llanelli Family'),
       ('MERTCV', 'Merthyr Tydfil Civil'),
       ('MERTFC', 'Merthyr Tydfil Family'),
       ('NEWPCV', 'Newport Civil'),
       ('NEWPFC', 'Newport Family'),
       ('PONTCV', 'Pontypridd Civil'),
       ('PONTFC', 'Pontypridd Family'),
       ('PORTCV', 'Port Talbot Civil'),
       ('PORTFC', 'Port Talbot Family'),
       ('SWANCV', 'Swansea Civil'),
       ('SWANFC', 'Swansea Family');

update enabled_court set name = 'Llandrindod Wells Magistrates' where id = 'LLNWMC';
