insert into enabled_court (id, name)
values ('ALDTCV', 'Aldershot Civil'),
       ('ALDTFM', 'Aldershot Family'),
       ('BRNLCV', 'Barnstaple Civil and Family'),
       ('BASECV', 'Basingstoke Civil'),
       ('BASEFM', 'Basingstoke Family'),
       ('BATHCV', 'Bath Civil'),
       ('BIRMCV', 'Birmingham Civil'),
       ('BIRMFM', 'Birmingham Family'),
       ('BDMNCV', 'Bodmin Civil'),
       ('BOSTCF', 'Boston Civil and Family'),
       ('BRMTCV', 'Bournemouth Civil'),
       ('BRMTFM', 'Bournemouth Family'),
       ('BRTLCV', 'Bristol Civil'),
       ('BRTLFM', 'Bristol Family'),
       ('COVTFM', 'Coventry and Warwickshire Family'),
       ('COVTCV', 'Coventry Civil'),
       ('DBCHCC', 'Derby and Chesterfield County'),
       ('DUDLCV', 'Dudley Civil'),
       ('DUDLFM', 'Dudley Family'),
       ('EXTRCV', 'Exeter Civil'),
       ('EXTRFM', 'Exeter Family'),
       ('GLTRCF', 'Gloucester Civil and Family'),
       ('HRFDCV', 'Hereford Civil'),
       ('IOWTCV', 'Isle of Wight Civil'),
       ('IOWTFM', 'Isle of Wight Family'),
       ('LEICCV', 'Leicester Civil'),
       ('LEICFM', 'Leicester Family'),
       ('LCLNCF', 'Lincoln Civil and Family'),
       ('MANSCV', 'Mansfield Civil'),
       ('MANSFM', 'Mansfield Family'),
       ('NORTCF', 'Northampton Civil and Family (Public Law)'),
       ('NORTFM', 'Northampton Family (Private Law)'),
       ('NOTMCF', 'Nottingham Civil and Family'),
       ('PLYMCC', 'Plymouth County'),
       ('PORTCF', 'Portsmouth Civil and Family'),
       ('SLBRCC', 'Salisbury County'),
       ('SMPTCF', 'Southampton Civil and Family'),
       ('STFDCV', 'Stafford Civil'),
       ('STFDFM', 'Stafford Family'),
       ('STKECV', 'Stoke on Trent Civil'),
       ('STKEFM', 'Stoke on Trent Family'),
       ('SWINCV', 'Swindon Civil'),
       ('SWINFM', 'Swindon Family'),
       ('TAUNCF', 'Taunton Civil and Family'),
       ('TELFCV', 'Telford Civil'),
       ('TELFFM', 'Telford Family'),
       ('TORQCC', 'Torquay and Newton County'),
       ('TRURCV', 'Truro Civil'),
       ('TRPRIV', 'Truro Family (Private Law)'),
       ('TRPUBL', 'Truro Family (Public Law)'),
       ('WALSCV', 'Walsall Civil'),
       ('WALSFM', 'Walsall Family'),
       ('WESTCV', 'Weston-Super-Mare Civil'),
       ('WEYMCV', 'Weymouth Civil'),
       ('WEYMFM', 'Weymouth Family'),
       ('WINRCV', 'Winchester Civil'),
       ('WINRFM', 'Winchester Family'),
       ('WOLVCF', 'Wolverhampton Civil and Family'),
       ('WORCCV', 'Worcester Civil'),
       ('WORCFM', 'Worcester Family'),
       ('YEOVCV', 'Yeovil Civil and Family');
	