DROP TABLE IF EXISTS VIDEO_LINK_APPOINTMENT;

CREATE TABLE VIDEO_LINK_APPOINTMENT
(
    ID             SERIAL PRIMARY KEY,
    BOOKING_ID     BIGINT NOT NULL,
    COURT          VARCHAR(50) NOT NULL,
    APPOINTMENT_ID BIGINT      NOT NULL,
    HEARING_TYPE  VARCHAR(30) NOT NULL
);

COMMENT ON TABLE VIDEO_LINK_APPOINTMENT IS 'Additional information for video link appointment';

CREATE INDEX VIDEO_LINK_APPOINTMENT_IDX ON VIDEO_LINK_APPOINTMENT (ID);
CREATE INDEX VIDEO_LINK_APPOINTMENT_APPOINTMENT_IDX ON VIDEO_LINK_APPOINTMENT (APPOINTMENT_ID);
