DROP TABLE IF EXISTS COURT_APPOINTMENT;

CREATE TABLE COURT_APPOINTMENT
(
    ID             SERIAL PRIMARY KEY,
    BOOKING_ID     BIGINT NOT NULL,
    COURT          VARCHAR(50) NOT NULL,
    APPOINTMENT_ID BIGINT      NOT NULL,
    HEARING_TYPE  VARCHAR(30) NOT NULL
);

COMMENT ON TABLE COURT_APPOINTMENT IS 'Additional court appointment information';

CREATE INDEX COURT_APPOINTMENT_IDX ON COURT_APPOINTMENT (ID);
CREATE INDEX COURT_APPOINTMENT_APPOINTMENT_IDX ON COURT_APPOINTMENT (APPOINTMENT_ID);
